import { expect, test } from '@playwright/test'
import { currency, getRecords, sum } from '../../NextCom - Front/src/lib/data'

test('analise regional preserva ranking e calcula metricas com filtros', async ({ page }) => {
  await page.goto('/')
  await page.locator('.all-countries').click()
  await page.getByPlaceholder('Buscar país ou código...').fill('Brasil')
  const trigger = page.getByRole('button', { name: 'Ver métricas de Brasil' })
  await trigger.focus()
  await page.keyboard.press('Enter')
  const detail = page.locator('.country-detail-dialog')
  await expect(detail.getByRole('heading', { name: 'Brasil', exact: true })).toBeVisible()
  await expect(detail.locator('.kpi-card')).toHaveCount(6)
  const expected = sum(getRecords(30, 'all').filter((row) => row.country === '076'))
  await expect(detail.locator('.kpi-value .sr-only').first()).toHaveText(currency(expected.spend))
  await page.keyboard.press('Escape')
  await expect(detail).toHaveCount(0)
  await expect(page.getByPlaceholder('Buscar país ou código...')).toHaveValue('Brasil')
  await page.keyboard.press('Escape')
  await page.getByRole('combobox', { name: 'Período do dashboard' }).click()
  await page.getByRole('option', { name: 'Últimos 7 dias' }).click()
  await page.getByRole('combobox', { name: 'Filtrar canal' }).click()
  await page.getByRole('option', { name: 'Instagram', exact: true }).click()
  await page.locator('.country-row').filter({ hasText: 'Brasil' }).click()
  const filtered = sum(getRecords(7, 'Instagram').filter((row) => row.country === '076'))
  await expect(detail.locator('.kpi-value .sr-only').first()).toHaveText(currency(filtered.spend))
  await detail.getByRole('button', { name: 'Voltar ao dashboard' }).click()
  await expect(detail).toHaveCount(0)
})

test('analise regional mobile com movimento reduzido', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 740 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  await page.locator('.all-countries').click()
  await page.getByRole('button', { name: 'Ver métricas de Portugal' }).click()
  const detail = page.locator('.country-detail-dialog')
  await expect(detail.getByRole('heading', { name: 'Portugal', exact: true })).toBeVisible()
  expect(await detail.evaluate((el) => el.scrollWidth <= el.clientWidth)).toBe(true)
  expect(await detail.locator('.region-scroll').evaluate((el) => el.scrollWidth <= el.clientWidth)).toBe(true)
  await detail.getByRole('heading', { name: 'Campanhas nesta região' }).scrollIntoViewIfNeeded()
  await expect(detail.locator('tbody tr')).not.toHaveCount(0)
  await detail.getByRole('button', { name: 'Voltar aos países' }).click()
  await expect(page.locator('.countries-dialog')).toBeVisible()
})
