import { expect, test } from '@playwright/test'

test('filtros, mapa vetorial, tema persistente e exportação', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Dashboard.' })).toBeVisible()
  await expect(page.locator('.kpi-card')).toHaveCount(6)
  expect(await page.locator('.world-map path').count()).toBeGreaterThan(170)
  const initialSpend = await page.locator('.kpi-value').first().textContent()
  await page.getByRole('combobox', { name: 'Período do dashboard' }).click()
  await page.getByRole('option', { name: 'Últimos 7 dias' }).click()
  await expect(page.locator('.kpi-value').first()).not.toHaveText(initialSpend!)
  const sevenDaySpend = await page.locator('.kpi-value').first().textContent()
  await page.getByRole('combobox', { name: 'Filtrar canal' }).click()
  await page.getByRole('option', { name: 'Instagram', exact: true }).click()
  await expect(page.locator('.kpi-value').first()).not.toHaveText(sevenDaySpend!)
  await page.getByRole('button', { name: /^Brasil:/ }).click()
  await expect(page.getByRole('button', { name: /^Brasil:/ })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('combobox', { name: 'Métrica do mapa' }).click()
  await page.getByRole('option', { name: 'ROAS', exact: true }).click()
  await expect(page.locator('.map-help')).toContainText('x')
  await page.getByRole('button', { name: 'Ampliar mapa' }).click()
  await page.getByRole('button', { name: 'Restaurar mapa' }).click()
  await expect(page.locator('.map-help')).toContainText('selecione um país')
  await page.getByRole('button', { name: 'Ativar tema claro' }).click()
  await expect(page.locator('html')).not.toHaveClass('dark')
  await page.reload()
  await expect(page.locator('html')).not.toHaveClass('dark')
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Exportar dados' }).click()
  expect((await download).suggestedFilename()).toContain('nextcom-demonstracao-30dias')
  expect(errors).toEqual([])
})

test('busca, estado vazio, detalhes e planejamento local', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('textbox', { name: 'Buscar campanha', exact: true }).fill('inexistente')
  await expect(page.getByText('Nenhuma campanha encontrada')).toBeVisible()
  await page.getByRole('button', { name: 'Limpar filtros', exact: true }).click()
  await page.getByRole('button', { name: 'Ver Conversões · Coleção essencial' }).click()
  await expect(page.getByRole('dialog')).toContainText('Detalhes demonstrativos')
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Planejamento', exact: true }).click()
  await page.getByLabel('Nome da campanha').fill('Campanha de teste')
  await page.getByLabel('Orçamento planejado').fill('1200')
  await page.getByLabel('Data de início').fill('2026-10-01')
  await page.getByRole('button', { name: 'Salvar rascunho' }).click()
  await expect(page.getByRole('dialog')).toContainText('Campanha de teste')
  await page.reload()
  await page.getByRole('button', { name: 'Planejamento', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('Campanha de teste')
  await page.getByRole('button', { name: 'Excluir rascunho Campanha de teste' }).click()
  await expect(page.getByRole('dialog')).not.toContainText('Campanha de teste')
})

test('mobile sem transbordamento e navegação acessível', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Dashboard.' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Abrir menu' }).click()
  await page.getByRole('button', { name: 'Integrações', exact: false }).click()
  await expect(page.getByRole('dialog')).toContainText('dados demonstrativos')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  const brazil = page.getByRole('button', { name: /^Brasil:/ })
  await brazil.focus()
  await page.keyboard.press('Enter')
  await expect(brazil).toHaveAttribute('aria-pressed', 'true')
})

test('API disponível sem expor credenciais', async ({ request }) => {
  const health = await request.get('/api/health')
  expect(health.ok()).toBe(true)
  expect(await health.json()).toEqual({ status: 'ok', service: 'nextcom-api' })
  const status = await request.get('/api/integrations/meta/status')
  expect(await status.json()).toMatchObject({ connected: false, mode: 'demo' })
  expect(await status.text()).not.toMatch(/META_ACCESS_TOKEN|META_APP_SECRET/)
})
